/**
 * Property Test: PDF Export Validation
 *
 * **Feature: sous-chef, PDF Export**
 * **Validates: Requirements 8.1**
 *
 * For any recipe, the PDF export SHALL produce a non-empty, valid PDF
 * containing the recipe title and ingredient names.
 *
 * Implementation note: The PdfService generates a pure text-based PDF using
 * the built-in TextEncoder (no canvas or browser APIs required), so these
 * tests run in Node.js/Vitest without any mocking.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fc from 'fast-check';
import { createDatabase, Database } from '../../src/db/database.js';
import { RecipeService } from '../../src/services/recipe-service.js';
import { PdfService } from '../../src/services/pdf-service.js';
import { minimalRecipeInputArb } from '../generators/recipe-generators.js';

/**
 * Decode a Uint8Array to a string so we can search for text content.
 * The PdfService embeds text as plain ASCII inside the PDF content stream,
 * so a simple UTF-8 decode lets us locate recipe fields in the raw bytes.
 */
function bufferToString(buf: Uint8Array): string {
  return new TextDecoder('utf-8', { fatal: false }).decode(buf);
}

describe('Property: PDF Export Validation', () => {
  let db: Database;
  let recipeService: RecipeService;
  let pdfService: PdfService;

  beforeEach(async () => {
    // Create fresh in-memory database for each test
    db = await createDatabase();
    recipeService = new RecipeService(db);
    pdfService = new PdfService(db);
  });

  afterEach(() => {
    db.close();
  });

  /**
   * Property 1: PDF Is Non-Empty
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * For any recipe, exportRecipeToPdf SHALL return a Uint8Array with length > 0.
   */
  it('Property 1: PDF is non-empty for any recipe', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        const recipe = recipeService.createRecipe(recipeInput);
        const pdfBytes = pdfService.exportRecipeToPdf(recipe.id);

        expect(pdfBytes).toBeInstanceOf(Uint8Array);
        expect(pdfBytes.length).toBeGreaterThan(0);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 2: Output is a valid PDF (starts with %PDF-)
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * For any recipe, the generated bytes SHALL begin with the PDF magic header
   * "%PDF-" which is the universal signature of a valid PDF document.
   */
  it('Property 2: Output starts with PDF magic header %PDF-', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        const recipe = recipeService.createRecipe(recipeInput);
        const pdfBytes = pdfService.exportRecipeToPdf(recipe.id);

        const raw = bufferToString(pdfBytes);
        expect(raw.startsWith('%PDF-')).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 3: PDF Contains Recipe Title
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * For any recipe, generating a PDF SHALL produce output that contains the
   * recipe title as text somewhere in the raw bytes.
   *
   * Note: The service truncates lines to 80 characters and escapes PDF special
   * characters (\, (, )). The title is embedded as "RECIPE: <title>" in the
   * content stream. We search for the first 60 characters of the escaped title
   * to stay well within the 80-char line limit.
   */
  it('Property 3: PDF contains the recipe title', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        const recipe = recipeService.createRecipe(recipeInput);
        const pdfBytes = pdfService.exportRecipeToPdf(recipe.id);

        const raw = bufferToString(pdfBytes);

        // Replicate the PDF escape applied in generatePdf so we search for
        // exactly what was written into the stream.
        const escapedTitle = recipe.title
          .replace(/\\/g, '\\\\')
          .replace(/\(/g, '\\(')
          .replace(/\)/g, '\\)');

        // The content line is "RECIPE: <title>" truncated to 80 chars.
        const expectedLine = `RECIPE: ${escapedTitle}`.substring(0, 80);

        expect(raw).toContain(expectedLine);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 4: PDF Contains Ingredient Names
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * For any recipe with at least one ingredient, generating a PDF SHALL include
   * each ingredient name somewhere in the output bytes.
   *
   * The ingredient line format is "  <qty> <unit> <name>" truncated to 80 chars.
   * We search for the (possibly truncated) escaped ingredient name to confirm
   * presence in the PDF stream.
   */
  it('Property 4: PDF contains ingredient names', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        // minimalRecipeInputArb guarantees at least 1 ingredient
        expect(recipeInput.ingredients.length).toBeGreaterThanOrEqual(1);

        const recipe = recipeService.createRecipe(recipeInput);
        const pdfBytes = pdfService.exportRecipeToPdf(recipe.id);
        const raw = bufferToString(pdfBytes);

        for (const ingredient of recipe.ingredients) {
          // Escape as the service does
          const escapedName = ingredient.name
            .replace(/\\/g, '\\\\')
            .replace(/\(/g, '\\(')
            .replace(/\)/g, '\\)');

          // Take up to 40 chars of the escaped name; the full line is at most
          // 80 chars and the prefix "  <qty> <unit> " consumes some of that.
          // Using the first 20 chars of the name avoids false negatives from
          // truncation while still being a meaningful check.
          const searchFragment = escapedName.substring(0, 20);
          if (searchFragment.length > 0) {
            expect(raw).toContain(searchFragment);
          }
        }
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 5: PDF Is Deterministic in Structure (approximately same size)
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * Generating a PDF twice for the same recipe SHALL produce outputs of
   * approximately the same byte size (within 5%). This allows for any minor
   * metadata variance while ensuring structural consistency.
   */
  it('Property 5: PDF size is deterministic (within 5%) across two generations', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        const recipe = recipeService.createRecipe(recipeInput);

        const pdf1 = pdfService.exportRecipeToPdf(recipe.id);
        const pdf2 = pdfService.exportRecipeToPdf(recipe.id);

        const sizeDiff = Math.abs(pdf1.length - pdf2.length);
        const maxAllowedDiff = Math.ceil(pdf1.length * 0.05);

        expect(sizeDiff).toBeLessThanOrEqual(maxAllowedDiff);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 6: PDF ends with %%EOF marker
   *
   * Requirements: 8.1 — Generate PDF with formatted recipe content
   *
   * A structurally complete PDF SHALL end with the "%%EOF" end-of-file marker
   * as required by the PDF specification.
   */
  it('Property 6: PDF ends with %%EOF marker', () => {
    fc.assert(
      fc.property(minimalRecipeInputArb, (recipeInput) => {
        const recipe = recipeService.createRecipe(recipeInput);
        const pdfBytes = pdfService.exportRecipeToPdf(recipe.id);

        const raw = bufferToString(pdfBytes);
        expect(raw.endsWith('%%EOF')).toBe(true);
      }),
      { numRuns: 100 }
    );
  });
});
