#!/usr/bin/env python3
"""Emit KitchenCore/Resources/foods.json — the bundled food table (ADR-009).

Nutrients are per 100 g edible portion from USDA FoodData Central (SR Legacy
or Foundation Foods; the USDA description is kept so each row can be looked
up). GI values are from the International Tables of Glycemic Index and
Glycemic Load Values (Atkinson, Foster-Powell & Brand-Miller, Diabetes Care
2008; 2021 update). `gi_basis` says whether the value is measured for that
food, a proxy from a close relative, or assumed for a low-carbohydrate food
not in the tables. Edit this file, rerun it, bump VERSION when values change.

Columns: id, name, keywords, usda, carbs, fiber, sodium_mg, sat_fat, gi,
gi_basis, unit_g (one piece), cup_g (one US cup).
"""
import json, sys, pathlib, unicodedata, re

def normalize(text):
    """Mirror of FoodMatcher.normalize: lowercase, accents folded, anything
    but letters, digits and apostrophes becomes a space, whitespace collapsed."""
    folded = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode().lower()
    folded = re.sub(r"\([^)]*\)", " ", folded)
    return " ".join(re.sub(r"[^a-z0-9']+", " ", folded).split())

VERSION = 2
F = []
def food(id, name, kw, usda, carbs, fiber, sodium, satfat, gi, basis, unit=None, cup=None):
    kw = list(dict.fromkeys(normalize(k) for k in kw))
    F.append(dict(id=id, name=name, keywords=kw, usda=usda, carbs=carbs, fiber=fiber, sodium=sodium,
                  satFat=satfat, gi=gi, giBasis=basis, unitGrams=unit, cupGrams=cup))

M, P, A = "measured", "proxy", "assumed"
# ---- Flours, grains, starches (raw / dry)
food("flour-white", "Flour, white, all-purpose", ["flour", "all-purpose flour", "all purpose flour", "plain flour", "bread flour", "cake flour", "pastry flour", "self-rising flour", "self-raising flour", "00 flour", "white flour"], "Wheat flour, white, all-purpose, enriched, bleached", 76.3, 2.7, 2, 0.2, 75, f"{P}: white wheat bread 75", None, 125)
food("flour-whole-wheat", "Flour, whole wheat", ["whole wheat flour", "wholemeal flour", "whole-wheat flour", "wholewheat flour", "spelt flour", "rye flour"], "Wheat flour, whole-grain", 72.0, 10.7, 2, 0.4, 74, f"{P}: whole wheat bread 74", None, 120)
food("flour-almond", "Almond flour", ["almond flour", "almond meal", "ground almonds"], "Nuts, almonds (ground)", 21.6, 12.5, 1, 3.7, 15, f"{A}: nuts, low", None, 96)
food("flour-coconut", "Coconut flour", ["coconut flour"], "Coconut flour (branded average)", 60.0, 38.5, 30, 13.0, 45, f"{A}: coconut, fibre-rich", None, 112)
food("flour-rice", "Rice flour", ["rice flour", "glutinous rice flour", "sweet rice flour"], "Rice flour, white", 80.1, 2.4, 0, 0.4, 73, f"{P}: white rice 73", None, 158)
food("cornmeal", "Cornmeal / polenta", ["cornmeal", "polenta", "corn meal", "masa harina", "grits"], "Cornmeal, degermed, enriched, yellow", 77.7, 7.3, 7, 0.6, 68, f"{M}: cornmeal porridge 68", None, 138)
food("semolina", "Semolina", ["semolina"], "Semolina, enriched", 72.8, 3.9, 1, 0.2, 55, f"{M}: semolina 55", None, 167)
food("oats", "Oats, rolled", ["oats", "rolled oats", "oatmeal", "quick oats", "old-fashioned oats", "steel cut oats", "steel-cut oats", "porridge oats"], "Cereals, oats, regular and quick, not fortified, dry", 66.3, 10.6, 2, 1.2, 55, f"{M}: porridge from rolled oats 55", None, 89)
food("rice-white", "Rice, white, long grain", ["rice", "white rice", "long grain rice", "long-grain rice", "sushi rice", "short grain rice"], "Rice, white, long-grain, regular, raw, unenriched", 79.9, 1.3, 5, 0.2, 73, f"{M}: white rice, boiled 73", None, 185)
food("rice-brown", "Rice, brown", ["brown rice"], "Rice, brown, long-grain, raw", 76.2, 3.4, 7, 0.5, 68, f"{M}: brown rice, boiled 68", None, 190)
food("rice-basmati", "Rice, basmati", ["basmati rice", "basmati"], "Rice, white, long-grain, regular, raw, unenriched", 79.9, 1.3, 5, 0.2, 58, f"{M}: basmati 58", None, 185)
food("rice-jasmine", "Rice, jasmine", ["jasmine rice"], "Rice, white, long-grain, regular, raw, unenriched", 79.9, 1.3, 5, 0.2, 89, f"{M}: jasmine rice 89", None, 185)
food("rice-arborio", "Rice, arborio", ["arborio rice", "arborio", "risotto rice", "carnaroli"], "Rice, white, short-grain, raw", 79.2, 2.8, 1, 0.2, 69, f"{M}: arborio 69", None, 200)
food("quinoa", "Quinoa", ["quinoa"], "Quinoa, uncooked", 64.2, 7.0, 5, 0.7, 53, f"{M}: quinoa 53", None, 170)
food("couscous", "Couscous", ["couscous"], "Couscous, dry", 77.4, 5.0, 10, 0.1, 65, f"{M}: couscous 65", None, 173)
food("bulgur", "Bulgur", ["bulgur", "bulgar", "burghul"], "Bulgur, dry", 75.9, 12.5, 17, 0.2, 48, f"{M}: bulgur 48", None, 140)
food("pasta", "Pasta, dry", ["pasta", "spaghetti", "penne", "macaroni", "fettuccine", "linguine", "rigatoni", "fusilli", "orzo", "farfalle", "tagliatelle", "lasagna noodles", "lasagne sheets", "elbow macaroni", "ziti", "gluten-free pasta", "angel hair"], "Pasta, dry, enriched", 74.7, 3.2, 6, 0.3, 49, f"{M}: spaghetti, white, boiled 49", None, 100)
food("pasta-whole-wheat", "Pasta, whole wheat, dry", ["whole wheat pasta", "wholemeal pasta", "whole wheat spaghetti"], "Pasta, whole-wheat, dry", 75.0, 9.0, 8, 0.3, 42, f"{M}: spaghetti, wholemeal, boiled 42", None, 100)
food("noodles-egg", "Egg noodles, dry", ["egg noodles"], "Noodles, egg, dry, enriched", 71.3, 3.3, 21, 1.2, 40, f"{M}: fettuccine, egg 40", None, 38)
food("noodles-rice", "Rice noodles, dry", ["rice noodles", "rice vermicelli", "pad thai noodles", "rice sticks"], "Rice noodles, dry", 80.2, 1.6, 182, 0.2, 53, f"{M}: rice noodles, dried, boiled 53", None, 90)
food("noodles-instant", "Instant noodles", ["instant noodles", "ramen noodles", "ramen"], "Noodles, instant (branded average, with seasoning)", 63.0, 2.5, 1700, 8.0, 47, f"{M}: instant noodles 47", 85, None)
food("bread-white", "Bread, white", ["bread", "white bread", "sandwich bread", "bread slices", "slices of bread", "baguette", "french bread", "italian bread", "dinner rolls", "rolls", "croutons", "crostini"], "Bread, white, commercially prepared", 49.0, 2.7, 490, 0.9, 75, f"{M}: white wheat bread 75", 28, None)
food("bread-whole-wheat", "Bread, whole wheat", ["whole wheat bread", "wholemeal bread", "whole grain bread", "brown bread"], "Bread, whole-wheat, commercially prepared", 43.1, 6.0, 455, 0.7, 74, f"{M}: whole wheat bread 74", 28, None)
food("bread-sourdough", "Bread, sourdough", ["sourdough", "sourdough bread"], "Bread, white, commercially prepared", 51.0, 2.5, 590, 0.5, 54, f"{M}: sourdough wheat bread 54", 45, None)
food("pita", "Pita bread", ["pita", "pita bread", "pitta", "naan", "flatbread"], "Bread, pita, white, enriched", 55.7, 2.2, 536, 0.2, 68, f"{M}: pita bread, white 68", 60, None)
food("tortilla-flour", "Tortilla, flour", ["flour tortillas", "flour tortilla", "tortillas", "tortilla", "wraps"], "Tortillas, ready-to-bake or -fry, flour", 48.7, 2.7, 736, 1.9, 30, f"{M}: wheat tortilla 30", 45, None)
food("tortilla-corn", "Tortilla, corn", ["corn tortillas", "corn tortilla"], "Tortillas, ready-to-bake or -fry, corn", 44.6, 6.3, 45, 0.5, 52, f"{M}: corn tortilla 52", 26, None)
food("bun", "Hamburger bun", ["hamburger buns", "burger buns", "buns", "hot dog buns", "brioche buns"], "Rolls, hamburger or hotdog, plain", 50.0, 2.1, 460, 0.9, 61, f"{M}: hamburger bun 61", 43, None)
food("breadcrumbs", "Breadcrumbs", ["breadcrumbs", "bread crumbs", "panko"], "Bread crumbs, dry, grated, plain", 71.9, 4.5, 732, 1.2, 75, f"{P}: white bread 75", None, 108)
food("crackers", "Crackers, saltine", ["crackers", "saltines", "saltine crackers", "ritz crackers"], "Crackers, saltines", 71.8, 2.8, 1070, 1.5, 74, f"{M}: soda crackers 74", 3, None)
food("graham-crackers", "Graham crackers", ["graham crackers", "graham cracker crumbs", "digestive biscuits"], "Crackers, graham, plain or honey", 77.0, 3.0, 470, 1.1, 70, f"{P}: digestive biscuit 70", 14, 84)
food("tortilla-chips", "Tortilla chips", ["tortilla chips", "corn chips"], "Snacks, tortilla chips, plain, white corn, salted", 65.3, 5.3, 421, 3.9, 42, f"{M}: corn chips, plain, salted 42", None, 60)
food("cornflakes", "Cornflakes", ["cornflakes", "corn flakes", "breakfast cereal", "cereal"], "Cereals ready-to-eat, corn flakes", 84.0, 3.3, 729, 0.1, 81, f"{M}: cornflakes 81", None, 28)
food("granola", "Granola", ["granola", "muesli"], "Cereals ready-to-eat, granola, homemade", 64.7, 7.2, 20, 3.3, 57, f"{M}: muesli 57", None, 122)
food("cornstarch", "Cornstarch", ["cornstarch", "corn starch", "cornflour", "arrowroot", "potato starch", "tapioca starch"], "Cornstarch", 91.3, 0.9, 9, 0.0, 85, f"{A}: refined starch, high", None, 128)
food("puff-pastry", "Puff pastry", ["puff pastry", "phyllo", "filo"], "Puff pastry, frozen, ready-to-bake", 45.7, 1.5, 253, 9.7, 67, f"{P}: croissant 67", 245, None)
food("pie-crust", "Pie crust", ["pie crust", "pie crusts", "pie dough", "shortcrust pastry"], "Pie crust, refrigerated, regular", 48.0, 1.0, 400, 7.0, 67, f"{P}: croissant 67", 230, None)
food("pizza-dough", "Pizza dough", ["pizza dough", "bread dough"], "Bread dough, pizza (branded average)", 49.0, 2.0, 600, 0.6, 75, f"{P}: white bread 75", 450, None)
food("yeast", "Yeast, active dry", ["yeast", "active dry yeast", "instant yeast", "dry yeast"], "Leavening agents, yeast, baker's, active dry", 41.2, 26.9, 51, 0.1, 30, f"{A}: yeast, small amounts", 7, 150)
food("sourdough-starter", "Sourdough starter", ["sourdough starter", "levain", "starter"], "Sourdough starter (flour and water, 100% hydration)", 38.0, 1.3, 1, 0.1, 54, f"{P}: sourdough bread 54", None, 240)
# ---- Sugars and sweets
food("sugar", "Sugar, granulated", ["sugar", "granulated sugar", "caster sugar", "white sugar", "superfine sugar", "cane sugar"], "Sugars, granulated", 100.0, 0.0, 1, 0.0, 65, f"{M}: sucrose 65", None, 200)
food("sugar-brown", "Sugar, brown", ["brown sugar", "light brown sugar", "dark brown sugar", "muscovado", "palm sugar", "coconut sugar", "demerara"], "Sugars, brown", 98.1, 0.0, 28, 0.0, 65, f"{P}: sucrose 65", None, 213)
food("sugar-powdered", "Sugar, powdered", ["powdered sugar", "icing sugar", "confectioners sugar", "confectioners' sugar"], "Sugars, powdered", 99.8, 0.0, 2, 0.0, 65, f"{P}: sucrose 65", None, 120)
food("honey", "Honey", ["honey"], "Honey", 82.4, 0.2, 4, 0.0, 61, f"{M}: honey (mean) 61", None, 340)
food("maple-syrup", "Maple syrup", ["maple syrup"], "Syrups, maple", 67.0, 0.0, 12, 0.0, 54, f"{M}: maple syrup 54", None, 312)
food("molasses", "Molasses", ["molasses", "treacle", "golden syrup"], "Molasses", 74.7, 0.0, 37, 0.0, 63, f"{P}: golden syrup 63", None, 340)
food("corn-syrup", "Corn syrup", ["corn syrup", "glucose syrup"], "Syrups, corn, light", 76.8, 0.0, 155, 0.0, 90, f"{P}: glucose syrup (mostly glucose)", None, 328)
food("agave", "Agave syrup", ["agave", "agave nectar", "agave syrup"], "Sweetener, syrup, agave", 76.4, 0.2, 4, 0.0, 15, f"{M}: agave nectar 15", None, 336)
food("jam", "Jam", ["jam", "jelly", "preserves", "marmalade", "fruit spread"], "Jams and preserves", 68.9, 1.1, 32, 0.0, 51, f"{M}: strawberry jam 51", None, 320)
food("chocolate-chips", "Chocolate chips, semisweet", ["chocolate chips", "semisweet chocolate", "semi-sweet chocolate", "chocolate", "chocolate chunks"], "Chocolate, dark, 45-59% cacao solids", 61.2, 7.0, 24, 18.5, 40, f"{M}: chocolate, plain 40", None, 170)
food("chocolate-dark", "Chocolate, dark (70–85%)", ["dark chocolate", "bittersweet chocolate", "70% chocolate", "unsweetened chocolate"], "Chocolate, dark, 70-85% cacao solids", 45.9, 10.9, 20, 24.5, 23, f"{M}: dark chocolate 23", None, 170)
food("chocolate-milk", "Chocolate, milk", ["milk chocolate", "white chocolate"], "Candies, milk chocolate", 59.4, 3.4, 79, 18.5, 43, f"{M}: milk chocolate 43", None, 170)
food("cocoa", "Cocoa powder, unsweetened", ["cocoa powder", "cocoa", "cacao powder", "cacao"], "Cocoa, dry powder, unsweetened", 57.9, 33.2, 21, 7.2, 20, f"{A}: cocoa, fibre-rich, low", None, 85)
food("condensed-milk", "Sweetened condensed milk", ["sweetened condensed milk", "condensed milk"], "Milk, canned, condensed, sweetened", 54.4, 0.0, 127, 5.5, 61, f"{M}: condensed milk, sweetened 61", 397, 306)
food("ice-cream", "Ice cream", ["ice cream", "vanilla ice cream"], "Ice creams, vanilla", 23.6, 0.7, 80, 6.8, 51, f"{M}: ice cream, regular 51", None, 132)
food("marshmallows", "Marshmallows", ["marshmallows", "marshmallow"], "Candies, marshmallows", 81.3, 0.1, 80, 0.0, 62, f"{P}: sucrose/glucose confectionery", 7, 50)
food("vanilla", "Vanilla extract", ["vanilla extract", "vanilla", "vanilla essence", "almond extract", "vanilla bean", "vanilla beans", "vanilla pod"], "Vanilla extract", 12.7, 0.0, 9, 0.0, 65, f"{P}: sucrose 65 (small amounts)", 3, 208)
# ---- Fats and dairy
food("butter", "Butter, salted", ["butter", "salted butter", "melted butter", "softened butter"], "Butter, salted", 0.1, 0.0, 643, 51.4, None, "no carbohydrate", 113, 227)
food("butter-unsalted", "Butter, unsalted", ["unsalted butter"], "Butter, without salt", 0.1, 0.0, 11, 51.4, None, "no carbohydrate", 113, 227)
food("ghee", "Ghee", ["ghee", "clarified butter"], "Butter oil, anhydrous", 0.0, 0.0, 2, 61.9, None, "no carbohydrate", None, 205)
food("margarine", "Margarine", ["margarine"], "Margarine, regular, 80% fat, stick", 0.7, 0.0, 654, 16.7, None, "negligible amounts", 113, 227)
food("shortening", "Shortening", ["shortening", "vegetable shortening", "crisco"], "Shortening, vegetable, household", 0.0, 0.0, 0, 25.0, None, "no carbohydrate", None, 191)
food("lard", "Lard", ["lard", "bacon fat", "bacon grease", "tallow", "duck fat"], "Lard", 0.0, 0.0, 0, 39.2, None, "no carbohydrate", None, 205)
food("oil-olive", "Olive oil", ["olive oil", "extra virgin olive oil", "extra-virgin olive oil", "evoo"], "Oil, olive, salad or cooking", 0.0, 0.0, 2, 13.8, None, "no carbohydrate", None, 216)
food("oil-vegetable", "Vegetable oil", ["oil", "vegetable oil", "cooking oil", "neutral oil", "corn oil", "soybean oil", "grapeseed oil"], "Oil, soybean, salad or cooking", 0.0, 0.0, 0, 15.6, None, "no carbohydrate", None, 218)
food("oil-canola", "Canola oil", ["canola oil", "rapeseed oil", "sunflower oil", "safflower oil"], "Oil, canola", 0.0, 0.0, 0, 7.4, None, "no carbohydrate", None, 218)
food("oil-coconut", "Coconut oil", ["coconut oil"], "Oil, coconut", 0.0, 0.0, 0, 82.5, None, "no carbohydrate", None, 218)
food("oil-sesame", "Sesame oil", ["sesame oil", "toasted sesame oil"], "Oil, sesame, salad or cooking", 0.0, 0.0, 0, 14.2, None, "no carbohydrate", None, 218)
food("oil-avocado", "Avocado oil", ["avocado oil"], "Oil, avocado", 0.0, 0.0, 0, 11.6, None, "no carbohydrate", None, 218)
food("oil-peanut", "Peanut oil", ["peanut oil"], "Oil, peanut, salad or cooking", 0.0, 0.0, 0, 16.9, None, "no carbohydrate", None, 216)
food("cooking-spray", "Cooking spray", ["cooking spray", "nonstick spray", "non-stick spray"], "Oil, PAM cooking spray, original", 0.0, 0.0, 0, 8.0, None, "no carbohydrate", None, 218)
food("milk-whole", "Milk, whole", ["milk", "whole milk", "full-fat milk", "full cream milk", "2% milk", "milk 2%"], "Milk, whole, 3.25% milkfat", 4.8, 0.0, 43, 1.9, 39, f"{M}: milk, full-fat 39", None, 244)
food("milk-skim", "Milk, skim", ["skim milk", "skimmed milk", "nonfat milk", "1% milk", "low-fat milk"], "Milk, nonfat, fluid", 5.0, 0.0, 42, 0.1, 37, f"{M}: milk, skim 37", None, 245)
food("buttermilk", "Buttermilk", ["buttermilk"], "Milk, buttermilk, fluid, cultured, lowfat", 4.8, 0.0, 105, 0.6, 39, f"{P}: milk 39", None, 245)
food("cream-heavy", "Cream, heavy", ["heavy cream", "whipping cream", "heavy whipping cream", "double cream", "cream", "single cream"], "Cream, fluid, heavy whipping", 2.8, 0.0, 27, 23.0, 39, f"{P}: milk 39 (little carbohydrate)", None, 238)
food("half-and-half", "Half and half", ["half and half", "half-and-half", "light cream"], "Cream, fluid, half and half", 4.3, 0.0, 41, 7.2, 39, f"{P}: milk 39", None, 242)
food("sour-cream", "Sour cream", ["sour cream", "crème fraîche", "creme fraiche"], "Cream, sour, cultured", 4.6, 0.0, 53, 10.4, 39, f"{P}: milk 39", None, 230)
food("yogurt", "Yogurt, plain", ["yogurt", "yoghurt", "plain yogurt", "natural yogurt"], "Yogurt, plain, whole milk", 4.7, 0.0, 46, 2.1, 36, f"{M}: yogurt, natural 36", None, 245)
food("yogurt-greek", "Greek yogurt, plain", ["greek yogurt", "greek yoghurt", "skyr", "labneh"], "Yogurt, Greek, plain, whole milk", 3.9, 0.0, 36, 2.9, 12, f"{M}: Greek yogurt 12", None, 245)
food("cream-cheese", "Cream cheese", ["cream cheese", "mascarpone"], "Cheese, cream", 5.5, 0.0, 314, 20.2, 39, f"{P}: milk 39 (little carbohydrate)", 226, 232)
food("cheese-cheddar", "Cheese, cheddar", ["cheese", "cheddar", "cheddar cheese", "shredded cheese", "monterey jack", "jack cheese", "colby", "gouda", "gruyere", "gruyère", "swiss cheese", "pepper jack", "provolone", "havarti"], "Cheese, cheddar", 3.1, 0.0, 653, 21.0, 15, f"{A}: dairy, little carbohydrate", None, 113)
food("cheese-mozzarella", "Cheese, mozzarella", ["mozzarella", "mozzarella cheese", "fresh mozzarella", "burrata"], "Cheese, mozzarella, whole milk", 2.2, 0.0, 486, 13.2, 15, f"{A}: dairy, little carbohydrate", None, 113)
food("cheese-parmesan", "Cheese, parmesan", ["parmesan", "parmigiano", "parmigiano-reggiano", "pecorino", "pecorino romano", "grana padano", "romano cheese", "asiago"], "Cheese, parmesan, hard", 3.2, 0.0, 1529, 16.4, 15, f"{A}: dairy, little carbohydrate", None, 100)
food("cheese-feta", "Cheese, feta", ["feta", "feta cheese", "goat cheese", "chèvre", "chevre", "blue cheese", "gorgonzola", "halloumi", "paneer", "queso fresco", "cotija"], "Cheese, feta", 4.1, 0.0, 917, 14.9, 15, f"{A}: dairy, little carbohydrate", None, 150)
food("ricotta", "Ricotta", ["ricotta", "ricotta cheese"], "Cheese, ricotta, whole milk", 3.0, 0.0, 84, 8.3, 15, f"{A}: dairy, little carbohydrate", None, 246)
food("cottage-cheese", "Cottage cheese", ["cottage cheese"], "Cheese, cottage, creamed, large or small curd", 3.4, 0.0, 364, 1.7, 15, f"{A}: dairy, little carbohydrate", None, 226)
food("evaporated-milk", "Evaporated milk", ["evaporated milk"], "Milk, canned, evaporated, whole", 10.0, 0.0, 106, 4.6, 39, f"{P}: milk 39", 354, 252)
food("milk-almond", "Almond milk, unsweetened", ["almond milk", "cashew milk", "nut milk"], "Beverages, almond milk, unsweetened", 1.3, 0.4, 72, 0.1, 25, f"{A}: nut milk, little carbohydrate", None, 240)
food("milk-oat", "Oat milk", ["oat milk"], "Beverages, oat milk (branded average)", 6.7, 0.8, 42, 0.2, 69, f"{M}: oat drink 69", None, 240)
food("milk-soy", "Soy milk", ["soy milk", "soya milk"], "Beverages, soy milk, unsweetened", 4.0, 0.5, 51, 0.2, 34, f"{M}: soy milk 34", None, 243)
food("coconut-milk", "Coconut milk, canned", ["coconut milk", "coconut cream", "canned coconut milk"], "Nuts, coconut milk, canned", 2.8, 0.0, 13, 18.9, 41, f"{A}: coconut, little carbohydrate", 400, 227)
food("cream-of-coconut", "Cream of coconut, sweetened", ["cream of coconut", "coconut cream sweetened"], "Cream of coconut, canned, sweetened (branded average)", 55.0, 0.0, 30, 14.0, 55, f"{A}: sweetened coconut", 425, 300)
food("coconut-water", "Coconut water", ["coconut water"], "Nuts, coconut water (liquid from coconuts)", 3.7, 1.1, 105, 0.2, 40, f"{A}: mildly sweet drink", None, 240)
food("eggs", "Egg, whole", ["egg", "eggs", "large eggs", "large egg", "whole eggs", "whole egg", "beaten egg", "beaten eggs"], "Egg, whole, raw, fresh", 0.7, 0.0, 142, 3.1, None, "negligible amounts", 50, 243)
food("egg-yolk", "Egg yolk", ["egg yolk", "egg yolks", "yolks", "yolk"], "Egg, yolk, raw, fresh", 3.6, 0.0, 48, 9.6, 15, f"{A}: egg, little carbohydrate", 17, 243)
food("egg-white", "Egg white", ["egg white", "egg whites", "whites"], "Egg, white, raw, fresh", 0.7, 0.0, 166, 0.0, None, "no carbohydrate", 33, 243)
# ---- Meat, fish, protein
food("chicken-breast", "Chicken breast, skinless", ["chicken breast", "chicken breasts", "boneless skinless chicken breast", "chicken tenders", "chicken cutlets"], "Chicken, broilers or fryers, breast, meat only, raw", 0.0, 0.0, 45, 0.6, None, "no carbohydrate", 174, 140)
food("chicken-thigh", "Chicken thigh", ["chicken thighs", "chicken thigh", "chicken legs", "chicken drumsticks", "drumsticks", "chicken wings", "wings"], "Chicken, broilers or fryers, thigh, meat and skin, raw", 0.0, 0.0, 84, 4.4, None, "no carbohydrate", 110, 140)
food("chicken", "Chicken, whole", ["chicken", "whole chicken", "rotisserie chicken", "cooked chicken", "shredded chicken"], "Chicken, broilers or fryers, meat and skin, raw", 0.0, 0.0, 70, 4.3, None, "no carbohydrate", 1400, 140)
food("turkey", "Turkey", ["turkey", "turkey breast", "ground turkey", "turkey mince"], "Turkey, ground, raw", 0.0, 0.0, 70, 2.5, None, "no carbohydrate", None, 140)
food("beef-ground", "Beef, ground (80/20)", ["ground beef", "minced beef", "beef mince", "hamburger meat", "ground chuck"], "Beef, ground, 80% lean meat / 20% fat, raw", 0.0, 0.0, 66, 7.6, None, "no carbohydrate", None, 225)
food("beef-ground-lean", "Beef, ground, lean (90/10)", ["lean ground beef", "extra lean ground beef", "ground sirloin", "93% lean ground beef"], "Beef, ground, 90% lean meat / 10% fat, raw", 0.0, 0.0, 66, 4.0, None, "no carbohydrate", None, 225)
food("beef", "Beef", ["beef", "beef chuck", "chuck roast", "stew meat", "beef stew meat", "stewing beef", "brisket", "short ribs", "beef short ribs", "roast beef", "pot roast"], "Beef, chuck, arm pot roast, separable lean and fat, raw", 0.0, 0.0, 66, 6.5, None, "no carbohydrate", None, None)
food("steak", "Beef steak", ["steak", "sirloin", "ribeye", "rib-eye", "flank steak", "skirt steak", "filet mignon", "beef tenderloin", "strip steak", "new york strip", "t-bone"], "Beef, top sirloin, steak, separable lean and fat, raw", 0.0, 0.0, 55, 4.0, None, "no carbohydrate", 225, None)
food("pork", "Pork shoulder", ["pork", "pork shoulder", "pork butt", "boston butt", "pork roast", "pork belly", "pork ribs", "spare ribs", "baby back ribs", "ribs"], "Pork, fresh, shoulder, whole, separable lean and fat, raw", 0.0, 0.0, 75, 5.5, None, "no carbohydrate", None, None)
food("pork-chop", "Pork chop / loin", ["pork chops", "pork chop", "pork loin", "pork tenderloin"], "Pork, fresh, loin, center loin (chops), separable lean and fat, raw", 0.0, 0.0, 53, 2.9, None, "no carbohydrate", 150, None)
food("pork-ground", "Pork, ground", ["ground pork", "pork mince", "minced pork"], "Pork, fresh, ground, raw", 0.0, 0.0, 56, 6.2, None, "no carbohydrate", None, 225)
food("bacon", "Bacon", ["bacon", "bacon strips", "slices of bacon", "bacon slices", "streaky bacon", "pancetta", "guanciale"], "Pork, cured, bacon, raw", 1.3, 0.0, 662, 12.5, 15, f"{A}: cured meat, little carbohydrate", 28, None)
food("sausage", "Sausage, pork", ["sausage", "sausages", "pork sausage", "bratwurst", "chorizo", "kielbasa", "andouille", "breakfast sausage", "sausage meat"], "Sausage, pork, fresh, raw", 2.7, 0.0, 739, 8.9, 15, f"{A}: sausage, little carbohydrate", 60, None)
food("sausage-italian", "Sausage, Italian", ["italian sausage", "italian sausages", "sweet italian sausage", "hot italian sausage"], "Sausage, Italian, pork, raw", 0.7, 0.0, 731, 10.0, 15, f"{A}: sausage, little carbohydrate", 85, None)
food("ham", "Ham, sliced", ["ham", "deli ham", "prosciutto", "canadian bacon", "deli turkey", "salami", "pepperoni"], "Ham, sliced, regular (approximately 11% fat)", 1.5, 0.0, 1200, 1.7, 15, f"{A}: cured meat, little carbohydrate", 28, 135)
food("hot-dogs", "Hot dogs", ["hot dogs", "hot dog", "frankfurters", "wieners"], "Frankfurter, beef and pork", 2.6, 0.0, 1090, 9.9, 15, f"{A}: cured meat, little carbohydrate", 45, None)
food("lamb", "Lamb", ["lamb", "ground lamb", "lamb shoulder", "lamb chops", "leg of lamb", "lamb mince"], "Lamb, domestic, shoulder, whole, separable lean and fat, raw", 0.0, 0.0, 60, 9.0, None, "no carbohydrate", None, None)
food("salmon", "Salmon", ["salmon", "salmon fillets", "salmon fillet", "trout", "mackerel", "sardines"], "Fish, salmon, Atlantic, farmed, raw", 0.0, 0.0, 59, 3.1, None, "no carbohydrate", 170, None)
food("fish-white", "Fish, white", ["fish", "white fish", "cod", "tilapia", "halibut", "haddock", "fish fillets", "fish fillet", "sea bass", "snapper", "pollock", "catfish", "sole"], "Fish, cod, Atlantic, raw", 0.0, 0.0, 54, 0.1, None, "no carbohydrate", 170, None)
food("anchovies", "Anchovies", ["anchovies", "anchovy", "anchovy paste", "anchovy fillets"], "Fish, anchovy, european, canned in oil, drained solids", 0.0, 0.0, 3668, 2.2, None, "no carbohydrate", 4, 150)
food("tuna-canned", "Tuna, canned", ["canned tuna", "tuna", "tinned tuna"], "Fish, tuna, light, canned in water, drained solids", 0.0, 0.0, 300, 0.2, None, "no carbohydrate", 120, 154)
food("shrimp", "Shrimp", ["shrimp", "prawns", "prawn", "scallops", "crab", "crab meat", "lobster", "squid", "calamari"], "Crustaceans, shrimp, raw", 0.9, 0.0, 119, 0.3, None, "negligible amounts", 12, 145)
food("tofu", "Tofu, firm", ["tofu", "firm tofu", "extra firm tofu", "silken tofu"], "Tofu, firm, prepared with calcium sulfate", 2.8, 0.3, 14, 1.2, 15, f"{M}: soy, low", 350, 252)
food("tempeh", "Tempeh", ["tempeh", "seitan"], "Tempeh", 7.6, 0.0, 9, 2.5, 15, f"{A}: soy, low", 227, 166)
# ---- Legumes, nuts, seeds
food("lentils", "Lentils, dry", ["lentils", "red lentils", "green lentils", "brown lentils", "black lentils", "dal", "dhal", "split peas", "yellow split peas"], "Lentils, raw", 63.4, 10.7, 6, 0.1, 32, f"{M}: lentils (mean) 32", None, 192)
food("chickpeas", "Chickpeas, canned", ["chickpeas", "garbanzo beans", "garbanzos", "canned chickpeas", "chick peas"], "Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained solids", 22.4, 6.5, 246, 0.3, 38, f"{M}: chickpeas, canned 38", 240, 164)
food("chickpeas-dry", "Chickpeas, dry", ["dried chickpeas", "dry chickpeas"], "Chickpeas (garbanzo beans, bengal gram), mature seeds, raw", 63.0, 12.2, 24, 0.6, 28, f"{M}: chickpeas, boiled 28", None, 200)
food("beans-black", "Black beans, canned", ["black beans", "canned black beans", "turtle beans"], "Beans, black, mature seeds, canned", 20.0, 7.0, 380, 0.1, 30, f"{M}: black beans 30", 240, 172)
food("beans-kidney", "Kidney beans, canned", ["kidney beans", "red kidney beans", "beans", "red beans", "canned beans"], "Beans, kidney, red, mature seeds, canned", 22.8, 6.4, 380, 0.1, 24, f"{M}: kidney beans 24", 240, 177)
food("beans-pinto", "Pinto beans, canned", ["pinto beans"], "Beans, pinto, mature seeds, canned", 26.2, 6.7, 380, 0.1, 45, f"{M}: pinto beans, canned 45", 240, 171)
food("beans-white", "White beans, canned", ["white beans", "cannellini beans", "cannellini", "navy beans", "great northern beans", "butter beans", "lima beans", "haricot beans"], "Beans, white, mature seeds, canned", 26.1, 6.3, 380, 0.1, 31, f"{M}: navy beans 31", 240, 180)
food("beans-refried", "Refried beans", ["refried beans"], "Refried beans, canned, traditional style", 15.0, 5.0, 500, 0.5, 38, f"{P}: pinto beans 38", 420, 238)
food("beans-baked", "Baked beans", ["baked beans"], "Beans, baked, canned, plain or vegetarian", 21.2, 5.5, 422, 0.2, 40, f"{M}: baked beans, canned 40", 415, 254)
food("beans-dry", "Beans, dry", ["dried beans", "dry beans", "dried kidney beans", "dried black beans", "dried pinto beans", "dried white beans"], "Beans, kidney, all types, mature seeds, raw", 60.0, 24.9, 24, 0.2, 28, f"{M}: kidney beans, boiled 28", None, 184)
food("edamame", "Edamame / soybeans", ["edamame", "soybeans", "soy beans"], "Edamame, frozen, unprepared", 8.9, 5.2, 6, 0.5, 15, f"{M}: soy beans 15", None, 155)
food("hummus", "Hummus", ["hummus", "houmous"], "Hummus, commercial", 14.3, 6.0, 379, 1.4, 6, f"{M}: hummus 6", None, 246)
food("peanut-butter", "Peanut butter", ["peanut butter"], "Peanut butter, smooth style, with salt", 22.3, 5.0, 429, 10.3, 14, f"{M}: peanut butter 14", None, 270)
food("nut-butter", "Almond / nut butter", ["almond butter", "cashew butter", "nut butter", "sunflower butter"], "Nut butter, almond, plain, without salt added", 18.8, 10.3, 7, 4.8, 15, f"{A}: nuts, low", None, 256)
food("tahini", "Tahini", ["tahini", "sesame paste"], "Seeds, sesame butter, tahini, from roasted and toasted kernels", 21.2, 9.3, 115, 7.5, 40, f"{A}: sesame, moderate", None, 240)
food("peanuts", "Peanuts", ["peanuts", "roasted peanuts", "peanut"], "Peanuts, all types, raw", 16.1, 8.5, 18, 6.8, 7, f"{M}: peanuts 7", None, 146)
food("almonds", "Almonds", ["almonds", "sliced almonds", "slivered almonds", "almond"], "Nuts, almonds", 21.6, 12.5, 1, 3.7, 15, f"{A}: nuts, low", 1.2, 143)
food("walnuts", "Walnuts", ["walnuts", "walnut", "chopped walnuts"], "Nuts, walnuts, english", 13.7, 6.7, 2, 6.1, 15, f"{A}: nuts, low", None, 117)
food("pecans", "Pecans", ["pecans", "pecan", "chopped pecans"], "Nuts, pecans", 13.9, 9.6, 0, 6.2, 15, f"{A}: nuts, low", None, 110)
food("cashews", "Cashews", ["cashews", "cashew", "cashew nuts"], "Nuts, cashew nuts, raw", 30.2, 3.3, 12, 7.8, 22, f"{M}: cashews 22", None, 137)
food("pistachios", "Pistachios", ["pistachios", "pistachio"], "Nuts, pistachio nuts, raw", 27.2, 10.6, 1, 5.9, 15, f"{A}: nuts, low", None, 123)
food("pine-nuts", "Pine nuts", ["pine nuts", "pignoli"], "Nuts, pine nuts, dried", 13.1, 3.7, 2, 4.9, 15, f"{A}: nuts, low", None, 135)
food("hazelnuts", "Hazelnuts", ["hazelnuts", "hazelnut", "filberts", "macadamia nuts", "macadamia", "brazil nuts", "mixed nuts", "nuts", "chopped nuts"], "Nuts, hazelnuts or filberts", 16.7, 9.7, 0, 4.5, 15, f"{A}: nuts, low", None, 120)
food("sunflower-seeds", "Sunflower seeds", ["sunflower seeds", "pumpkin seeds", "pepitas", "hemp seeds", "hemp hearts"], "Seeds, sunflower seed kernels, dried", 20.0, 8.6, 9, 4.5, 15, f"{A}: seeds, low", None, 140)
food("sesame-seeds", "Sesame seeds", ["sesame seeds", "sesame", "poppy seeds"], "Seeds, sesame seeds, whole, dried", 23.4, 11.8, 11, 7.0, 15, f"{A}: seeds, low", None, 144)
food("chia", "Chia seeds", ["chia seeds", "chia"], "Seeds, chia seeds, dried", 42.1, 34.4, 16, 3.3, 10, f"{A}: chia, mostly fibre", None, 163)
food("flaxseed", "Flaxseed", ["flaxseed", "flax seed", "flax seeds", "ground flaxseed", "linseed", "flax meal"], "Seeds, flaxseed", 28.9, 27.3, 30, 3.7, 10, f"{A}: flax, mostly fibre", None, 150)
food("coconut-shredded", "Coconut, dried, unsweetened", ["shredded coconut", "desiccated coconut", "coconut flakes", "unsweetened coconut", "coconut"], "Nuts, coconut meat, dried (desiccated), not sweetened", 23.7, 16.3, 37, 57.2, 45, f"{A}: coconut, moderate", None, 93)
food("coconut-sweetened", "Coconut, sweetened, flaked", ["sweetened coconut", "sweetened shredded coconut", "sweetened coconut flakes"], "Nuts, coconut meat, dried (desiccated), sweetened, flaked, packaged", 51.9, 4.5, 262, 29.3, 55, f"{A}: sweetened coconut", None, 85)
# ---- Vegetables
food("onion", "Onion", ["onion", "onions", "yellow onion", "yellow onions", "white onion", "red onion", "red onions", "sweet onion", "vidalia"], "Onions, raw", 9.3, 1.7, 4, 0.0, 10, f"{A}: onion, low", 110, 160)
food("garlic", "Garlic", ["garlic", "garlic cloves", "cloves garlic", "cloves of garlic", "clove garlic", "clove of garlic", "minced garlic", "garlic clove"], "Garlic, raw", 33.1, 2.1, 17, 0.1, 30, f"{A}: garlic, small amounts", 3, 136)
food("shallot", "Shallot", ["shallot", "shallots"], "Shallots, raw", 16.8, 3.2, 12, 0.0, 15, f"{A}: allium, low", 30, 160)
food("scallion", "Scallion / green onion", ["green onions", "green onion", "scallions", "scallion", "spring onions", "spring onion"], "Onions, spring or scallions (includes tops and bulb), raw", 7.3, 2.6, 16, 0.0, 15, f"{A}: allium, low", 15, 100)
food("leek", "Leek", ["leek", "leeks"], "Leeks, (bulb and lower leaf-portion), raw", 14.2, 1.8, 20, 0.0, 15, f"{A}: allium, low", 89, 89)
food("tomato", "Tomato", ["tomato", "tomatoes", "roma tomatoes", "roma tomato", "plum tomatoes", "cherry tomatoes", "grape tomatoes", "vine tomatoes", "beefsteak tomato", "fresh tomatoes"], "Tomatoes, red, ripe, raw, year round average", 3.9, 1.2, 5, 0.0, 15, f"{A}: tomato, low", 123, 180)
food("tomatoes-canned", "Tomatoes, canned", ["canned tomatoes", "diced tomatoes", "crushed tomatoes", "whole peeled tomatoes", "chopped tomatoes", "can of tomatoes", "tinned tomatoes", "fire-roasted tomatoes", "stewed tomatoes", "tomato passata", "passata"], "Tomatoes, red, ripe, canned, packed in tomato juice", 4.1, 1.9, 130, 0.0, 15, f"{A}: tomato, low", 400, 240)
food("tomato-paste", "Tomato paste", ["tomato paste", "tomato purée", "tomato puree", "tomato concentrate"], "Tomato products, canned, paste, without salt added", 18.9, 4.1, 59, 0.1, 20, f"{A}: tomato, low", 170, 262)
food("tomato-sauce", "Tomato sauce, canned", ["tomato sauce", "tomato sauce (canned)", "canned tomato sauce"], "Tomato products, canned, sauce", 5.3, 1.5, 474, 0.1, 20, f"{A}: tomato, low", 227, 245)
food("marinara", "Marinara / pasta sauce", ["marinara", "marinara sauce", "pasta sauce", "spaghetti sauce", "pizza sauce"], "Sauce, pasta, spaghetti/marinara, ready-to-serve", 7.0, 1.8, 460, 0.3, 25, f"{A}: tomato sauce, low", 680, 250)
food("ketchup", "Ketchup", ["ketchup", "catsup", "tomato ketchup"], "Catsup", 27.4, 0.3, 907, 0.0, 55, f"{A}: sweetened tomato", None, 272)
food("salsa", "Salsa", ["salsa", "pico de gallo"], "Sauce, salsa, ready-to-serve", 7.0, 1.9, 430, 0.0, 20, f"{A}: tomato, low", 450, 260)
food("potato", "Potato", ["potato", "potatoes", "russet potatoes", "russet potato", "yukon gold potatoes", "yukon gold", "red potatoes", "baby potatoes", "new potatoes", "fingerling potatoes", "gold potatoes"], "Potatoes, russet, flesh and skin, raw", 18.1, 1.3, 5, 0.0, 78, f"{M}: potato, boiled (mean) 78", 170, 150)
food("sweet-potato", "Sweet potato", ["sweet potato", "sweet potatoes", "yam", "yams", "kumara"], "Sweet potato, raw, unprepared", 20.1, 3.0, 55, 0.0, 63, f"{M}: sweet potato, boiled 63", 130, 133)
food("carrot", "Carrot", ["carrot", "carrots", "baby carrots", "shredded carrots"], "Carrots, raw", 9.6, 2.8, 69, 0.0, 39, f"{M}: carrots, boiled 39", 61, 128)
food("celery", "Celery", ["celery", "celery stalks", "celery stalk", "celery ribs"], "Celery, raw", 3.0, 1.6, 80, 0.0, 15, f"{A}: vegetable, low", 40, 101)
food("bell-pepper", "Bell pepper", ["bell pepper", "bell peppers", "red pepper", "red peppers", "green pepper", "green peppers", "capsicum", "red bell pepper", "green bell pepper", "yellow pepper", "orange pepper", "sweet pepper", "roasted red peppers"], "Peppers, sweet, red, raw", 6.0, 2.1, 4, 0.0, 15, f"{A}: vegetable, low", 119, 149)
food("chili-pepper", "Chili pepper", ["jalapeño", "jalapeno", "jalapeños", "jalapenos", "serrano", "chili", "chilies", "chillies", "chilli", "chile", "chiles", "green chiles", "green chilies", "habanero", "thai chili", "bird's eye chili", "poblano", "chipotle", "chipotles in adobo", "chipotle peppers"], "Peppers, jalapeno, raw", 6.5, 2.8, 3, 0.0, 15, f"{A}: vegetable, low", 14, 90)
food("broccoli", "Broccoli", ["broccoli", "broccolini", "broccoli florets"], "Broccoli, raw", 6.6, 2.6, 33, 0.0, 15, f"{A}: vegetable, low", 300, 91)
food("cauliflower", "Cauliflower", ["cauliflower", "cauliflower florets", "cauliflower rice", "riced cauliflower"], "Cauliflower, raw", 5.0, 2.0, 30, 0.1, 15, f"{A}: vegetable, low", 590, 107)
food("spinach", "Spinach", ["spinach", "baby spinach", "frozen spinach", "swiss chard", "chard", "arugula", "rocket", "watercress"], "Spinach, raw", 3.6, 2.2, 79, 0.1, 15, f"{A}: vegetable, low", 280, 30)
food("kale", "Kale", ["kale", "collard greens", "collards", "mustard greens", "bok choy", "pak choi"], "Kale, raw", 4.4, 4.1, 53, 0.1, 15, f"{A}: vegetable, low", 200, 40)
food("lettuce", "Lettuce", ["lettuce", "romaine", "romaine lettuce", "iceberg lettuce", "mixed greens", "salad greens", "spring mix", "butter lettuce", "endive", "radicchio"], "Lettuce, cos or romaine, raw", 3.3, 2.1, 8, 0.0, 15, f"{A}: vegetable, low", 500, 47)
food("cabbage", "Cabbage", ["cabbage", "green cabbage", "red cabbage", "napa cabbage", "savoy cabbage", "coleslaw mix", "sauerkraut", "brussels sprouts"], "Cabbage, raw", 5.8, 2.5, 18, 0.0, 15, f"{A}: vegetable, low", 900, 89)
food("zucchini", "Zucchini / summer squash", ["zucchini", "courgette", "courgettes", "yellow squash", "summer squash"], "Squash, summer, zucchini, includes skin, raw", 3.1, 1.0, 8, 0.0, 15, f"{A}: vegetable, low", 196, 124)
food("eggplant", "Eggplant", ["eggplant", "aubergine", "eggplants", "aubergines"], "Eggplant, raw", 5.9, 3.0, 2, 0.0, 15, f"{A}: vegetable, low", 500, 82)
food("cucumber", "Cucumber", ["cucumber", "cucumbers", "english cucumber", "persian cucumbers"], "Cucumber, with peel, raw", 3.6, 0.5, 2, 0.0, 15, f"{A}: vegetable, low", 200, 104)
food("mushrooms", "Mushrooms", ["mushrooms", "mushroom", "button mushrooms", "cremini", "cremini mushrooms", "baby bella", "portobello", "shiitake", "shiitake mushrooms", "oyster mushrooms", "porcini"], "Mushrooms, white, raw", 3.3, 1.0, 5, 0.1, 15, f"{A}: vegetable, low", 18, 70)
food("green-beans", "Green beans", ["green beans", "string beans", "french beans", "haricots verts", "snap beans"], "Beans, snap, green, raw", 7.0, 2.7, 6, 0.0, 15, f"{A}: vegetable, low", None, 100)
food("peas", "Peas, green", ["peas", "green peas", "frozen peas", "sweet peas", "petite peas", "garden peas"], "Peas, green, frozen, unprepared", 13.6, 4.5, 108, 0.1, 51, f"{M}: peas, green 51", None, 134)
food("snap-peas", "Snap / snow peas", ["sugar snap peas", "snap peas", "snow peas", "mangetout"], "Peas, edible-podded, raw", 7.6, 2.6, 4, 0.0, 15, f"{A}: vegetable, low", None, 63)
food("corn", "Corn, sweet", ["corn", "sweet corn", "corn kernels", "frozen corn", "corn on the cob", "ears of corn", "canned corn", "creamed corn"], "Corn, sweet, yellow, raw", 18.7, 2.7, 15, 0.3, 52, f"{M}: sweet corn 52", 90, 145)
food("avocado", "Avocado", ["avocado", "avocados", "guacamole"], "Avocados, raw, all commercial varieties", 8.5, 6.7, 7, 2.1, 15, f"{A}: avocado, low", 150, 150)
food("squash-winter", "Squash, winter", ["butternut squash", "butternut", "acorn squash", "winter squash", "kabocha", "delicata squash", "spaghetti squash", "squash"], "Squash, winter, butternut, raw", 11.7, 2.0, 4, 0.0, 51, f"{M}: butternut squash 51", 900, 140)
food("pumpkin", "Pumpkin purée", ["pumpkin", "pumpkin puree", "pumpkin purée", "canned pumpkin"], "Pumpkin, canned, without salt", 8.1, 2.9, 5, 0.2, 64, f"{M}: pumpkin, boiled 64", 425, 245)
food("asparagus", "Asparagus", ["asparagus", "asparagus spears"], "Asparagus, raw", 3.9, 2.1, 2, 0.0, 15, f"{A}: vegetable, low", 16, 134)
food("beet", "Beet", ["beet", "beets", "beetroot", "beetroots"], "Beets, raw", 9.6, 2.8, 78, 0.0, 64, f"{M}: beetroot 64", 82, 136)
food("radish", "Radish / turnip", ["radish", "radishes", "turnip", "turnips", "daikon", "kohlrabi", "fennel", "fennel bulb", "artichoke", "artichoke hearts", "okra", "bamboo shoots", "water chestnuts", "bean sprouts", "sprouts"], "Radishes, raw", 3.4, 1.6, 39, 0.0, 15, f"{A}: vegetable, low", 5, 116)
food("parsnip", "Parsnip / root vegetables", ["parsnip", "parsnips", "rutabaga", "swede", "celeriac", "celery root", "plantain", "cassava", "yuca", "taro"], "Parsnips, raw", 18.0, 4.9, 10, 0.1, 52, f"{M}: parsnip 52", 133, 133)
food("ginger", "Ginger, fresh", ["ginger", "fresh ginger", "ginger root", "grated ginger", "minced ginger", "galangal", "lemongrass"], "Ginger root, raw", 17.8, 2.0, 13, 0.1, 15, f"{A}: aromatic, small amounts", 15, 96)
food("olives", "Olives", ["olives", "kalamata olives", "black olives", "green olives", "olive", "capers"], "Olives, ripe, canned (small-extra large)", 6.3, 3.2, 735, 1.4, 15, f"{A}: olive, low", 4, 134)
food("pickles", "Pickles", ["pickles", "dill pickles", "pickle", "gherkins", "cornichons", "pickled jalapeños", "pickled onions", "kimchi"], "Pickles, cucumber, dill or kosher dill", 2.4, 1.2, 809, 0.1, 15, f"{A}: vegetable, low", 65, 155)
food("herbs-fresh", "Herbs, fresh", ["parsley", "cilantro", "coriander leaves", "fresh coriander", "basil", "fresh basil", "thai basil", "basil leaves", "mint", "mint leaves", "fresh mint", "dill", "fresh dill", "chives", "fresh thyme", "thyme sprigs", "fresh rosemary", "rosemary sprigs", "fresh oregano", "sage leaves", "fresh sage", "tarragon", "fresh herbs", "herbs", "thyme", "rosemary", "sage", "oregano leaves", "basil sprigs", "curry leaves", "kaffir lime leaves", "lime leaves"], "Parsley, fresh", 6.3, 3.3, 56, 0.1, 15, f"{A}: herbs, small amounts", 60, 40)
# ---- Fruit
food("lemon", "Lemon", ["lemon", "lemons", "lemon zest", "zest of lemon", "lemon wedges"], "Lemons, raw, without peel", 9.3, 2.8, 2, 0.0, 15, f"{A}: citrus, low", 58, 212)
food("lemon-juice", "Lemon juice", ["lemon juice", "juice of lemon", "fresh lemon juice"], "Lemon juice, raw", 6.9, 0.3, 1, 0.0, 20, f"{A}: citrus juice, low", None, 244)
food("lime", "Lime", ["lime", "limes", "lime zest", "lime wedges"], "Limes, raw", 10.5, 2.8, 2, 0.0, 15, f"{A}: citrus, low", 67, 200)
food("lime-juice", "Lime juice", ["lime juice", "juice of lime", "fresh lime juice"], "Lime juice, raw", 8.4, 0.4, 2, 0.0, 20, f"{A}: citrus juice, low", None, 246)
food("orange", "Orange", ["orange", "oranges", "clementine", "clementines", "mandarin", "mandarins", "tangerine", "grapefruit", "orange zest"], "Oranges, raw, all commercial varieties", 11.8, 2.4, 0, 0.0, 43, f"{M}: orange 43", 131, 180)
food("orange-juice", "Orange juice", ["orange juice", "oj", "apple juice", "fruit juice", "pineapple juice", "cranberry juice", "grape juice"], "Orange juice, raw", 10.4, 0.2, 1, 0.0, 50, f"{M}: orange juice 50", None, 248)
food("apple", "Apple", ["apple", "apples", "granny smith", "honeycrisp", "gala apples"], "Apples, raw, with skin", 13.8, 2.4, 1, 0.0, 36, f"{M}: apple (mean) 36", 182, 125)
food("applesauce", "Applesauce", ["applesauce", "apple sauce", "apple purée", "apple puree"], "Applesauce, canned, unsweetened", 11.3, 1.1, 2, 0.0, 40, f"{P}: apple 36 (puréed)", None, 244)
food("banana", "Banana", ["banana", "bananas", "ripe bananas", "mashed banana", "plantains"], "Bananas, raw", 22.8, 2.6, 1, 0.1, 51, f"{M}: banana (mean) 51", 118, 225)
food("strawberries", "Strawberries", ["strawberries", "strawberry"], "Strawberries, raw", 7.7, 2.0, 1, 0.0, 40, f"{M}: strawberries 40", 12, 152)
food("blueberries", "Blueberries", ["blueberries", "blueberry", "blackberries", "mixed berries", "berries", "frozen berries"], "Blueberries, raw", 14.5, 2.4, 1, 0.0, 53, f"{M}: blueberries 53", None, 148)
food("raspberries", "Raspberries", ["raspberries", "raspberry", "cranberries", "fresh cranberries"], "Raspberries, raw", 11.9, 6.5, 1, 0.0, 25, f"{A}: berries, fibre-rich, low", None, 123)
food("grapes", "Grapes", ["grapes", "grape", "red grapes", "green grapes"], "Grapes, red or green (European type), raw", 18.1, 0.9, 2, 0.1, 46, f"{M}: grapes (mean) 46", 5, 151)
food("pineapple", "Pineapple", ["pineapple", "pineapple chunks", "crushed pineapple"], "Pineapple, raw, all varieties", 13.1, 1.4, 1, 0.0, 59, f"{M}: pineapple (mean) 59", 900, 165)
food("mango", "Mango", ["mango", "mangoes", "mangos", "papaya", "kiwi", "kiwis", "kiwifruit"], "Mangos, raw", 15.0, 1.6, 1, 0.1, 51, f"{M}: mango (mean) 51", 200, 165)
food("peach", "Peach / stone fruit", ["peach", "peaches", "nectarine", "nectarines", "apricot", "apricots", "plum", "plums"], "Peaches, raw", 9.5, 1.5, 0, 0.0, 42, f"{M}: peach (mean) 42", 150, 154)
food("pear", "Pear", ["pear", "pears"], "Pears, raw", 15.2, 3.1, 1, 0.0, 38, f"{M}: pear (mean) 38", 178, 140)
food("cherries", "Cherries", ["cherries", "cherry", "sweet cherries", "pitted cherries"], "Cherries, sweet, raw", 16.0, 2.1, 0, 0.1, 25, f"{A}: cherries, low", 8, 138)
food("watermelon", "Watermelon", ["watermelon", "melon", "cantaloupe", "honeydew"], "Watermelon, raw", 7.6, 0.4, 1, 0.0, 76, f"{M}: watermelon 76", None, 152)
food("dates", "Dates", ["dates", "medjool dates", "pitted dates", "figs", "dried figs", "prunes"], "Dates, medjool", 75.0, 6.7, 1, 0.0, 42, f"{M}: dates (mean) 42", 24, 147)
food("raisins", "Raisins", ["raisins", "sultanas", "currants", "dried currants"], "Raisins, seedless", 79.2, 3.7, 11, 0.1, 64, f"{M}: raisins 64", None, 149)
food("cranberries-dried", "Cranberries, dried", ["dried cranberries", "craisins", "dried cherries", "dried blueberries"], "Cranberries, dried, sweetened", 82.4, 5.3, 3, 0.1, 64, f"{P}: raisins 64", None, 120)
food("apricots-dried", "Apricots, dried", ["dried apricots", "dried apricot"], "Apricots, dried, sulfured, uncooked", 62.6, 7.3, 10, 0.0, 31, f"{M}: dried apricots 31", 8, 130)
food("tamarind", "Tamarind paste", ["tamarind paste", "tamarind", "tamarind concentrate"], "Tamarinds, raw", 62.5, 5.1, 28, 0.3, 40, f"{A}: fruit paste, moderate", None, 260)
# ---- Condiments, sauces, stock, seasonings
food("soy-sauce", "Soy sauce", ["soy sauce", "tamari", "shoyu", "light soy sauce", "dark soy sauce", "coconut aminos", "liquid aminos"], "Soy sauce made from soy and wheat (shoyu)", 4.9, 0.8, 5493, 0.1, 30, f"{A}: fermented sauce, small amounts", None, 255)
food("fish-sauce", "Fish sauce", ["fish sauce", "nam pla"], "Sauce, fish, ready-to-serve", 3.6, 0.0, 7851, 0.0, 30, f"{A}: fermented sauce, small amounts", None, 257)
food("worcestershire", "Worcestershire sauce", ["worcestershire sauce", "worcestershire"], "Sauce, worcestershire", 19.5, 0.0, 980, 0.0, 55, f"{A}: sweetened sauce, small amounts", None, 264)
food("hot-sauce", "Hot sauce", ["hot sauce", "tabasco", "frank's red hot", "cholula", "buffalo sauce"], "Sauce, ready-to-serve, pepper or hot", 1.8, 0.3, 2643, 0.0, 30, f"{A}: chili sauce, small amounts", None, 240)
food("sriracha", "Sriracha", ["sriracha", "chili garlic sauce", "sambal oelek", "sambal", "gochujang", "harissa", "chili crisp"], "Sauce, sriracha (branded average)", 19.2, 2.2, 2124, 0.0, 30, f"{A}: chili sauce, small amounts", None, 260)
food("mustard", "Mustard, yellow", ["mustard", "yellow mustard", "whole grain mustard", "wholegrain mustard"], "Mustard, prepared, yellow", 5.3, 4.0, 1104, 0.2, 30, f"{A}: condiment, small amounts", None, 250)
food("mustard-dijon", "Mustard, Dijon", ["dijon mustard", "dijon"], "Mustard, prepared, Dijon (branded average)", 5.0, 3.0, 1900, 0.2, 30, f"{A}: condiment, small amounts", None, 250)
food("mayonnaise", "Mayonnaise", ["mayonnaise", "mayo", "aioli"], "Mayonnaise, regular", 0.6, 0.0, 635, 11.7, None, "negligible amounts", None, 220)
food("vinegar", "Vinegar", ["vinegar", "white vinegar", "apple cider vinegar", "cider vinegar", "rice vinegar", "rice wine vinegar", "red wine vinegar", "white wine vinegar", "sherry vinegar", "champagne vinegar", "distilled vinegar", "malt vinegar"], "Vinegar, cider", 0.9, 0.0, 5, 0.0, None, "negligible amounts", None, 239)
food("vinegar-balsamic", "Vinegar, balsamic", ["balsamic vinegar", "balsamic", "balsamic glaze"], "Vinegar, balsamic", 17.0, 0.0, 23, 0.0, 40, f"{A}: sweet vinegar, small amounts", None, 255)
food("broth-chicken", "Broth / stock", ["chicken broth", "chicken stock", "broth", "stock", "vegetable broth", "vegetable stock", "bone broth", "fish stock", "dashi", "turkey stock"], "Soup, chicken broth, ready-to-serve", 0.9, 0.0, 343, 0.2, None, "negligible amounts", 411, 240)
food("broth-beef", "Beef broth", ["beef broth", "beef stock", "beef bone broth"], "Soup, beef broth, ready-to-serve", 0.4, 0.0, 372, 0.1, None, "negligible amounts", 411, 240)
food("broth-low-sodium", "Broth, low sodium", ["low sodium chicken broth", "low-sodium chicken broth", "low sodium broth", "low-sodium broth", "reduced sodium chicken broth", "low sodium vegetable broth", "unsalted stock", "unsalted chicken stock", "low sodium beef broth"], "Soup, chicken broth, low sodium, canned", 0.9, 0.0, 30, 0.2, None, "negligible amounts", 411, 240)
food("bouillon", "Bouillon", ["bouillon", "bouillon cube", "bouillon cubes", "stock cube", "stock cubes", "chicken bouillon", "beef bouillon", "better than bouillon", "bouillon powder"], "Soup, beef broth, bouillon, dry, cubes", 15.0, 0.0, 24000, 2.0, 30, f"{A}: bouillon, small amounts", 4, 150)
food("condensed-soup", "Condensed cream soup", ["cream of mushroom soup", "cream of chicken soup", "cream of celery soup", "condensed soup", "condensed cream of mushroom"], "Soup, cream of mushroom, canned, condensed", 7.3, 0.5, 700, 2.0, 40, f"{A}: thickened soup, moderate", 298, 250)
food("bbq-sauce", "Barbecue sauce", ["bbq sauce", "barbecue sauce", "barbeque sauce"], "Sauce, barbecue", 40.8, 0.9, 815, 0.1, 55, f"{A}: sweetened sauce", None, 286)
food("teriyaki", "Teriyaki sauce", ["teriyaki sauce", "teriyaki"], "Sauce, teriyaki, ready-to-serve", 15.6, 0.1, 3833, 0.0, 55, f"{A}: sweetened soy sauce", None, 280)
food("hoisin", "Hoisin sauce", ["hoisin sauce", "hoisin", "plum sauce", "sweet chili sauce", "sweet chilli sauce"], "Sauce, hoisin, ready-to-serve", 44.1, 2.8, 1615, 0.6, 55, f"{A}: sweetened sauce", None, 260)
food("oyster-sauce", "Oyster sauce", ["oyster sauce"], "Sauce, oyster, ready-to-serve", 10.9, 0.3, 2733, 0.0, 55, f"{A}: sweetened sauce, small amounts", None, 260)
food("miso", "Miso", ["miso", "miso paste", "white miso", "red miso"], "Miso", 25.4, 5.4, 3728, 1.0, 30, f"{A}: fermented soy, small amounts", None, 275)
food("curry-paste", "Curry paste", ["curry paste", "red curry paste", "green curry paste", "thai curry paste", "massaman curry paste", "yellow curry paste"], "Curry paste, Thai (branded average)", 10.0, 2.0, 2300, 0.5, 25, f"{A}: paste, small amounts", 113, 260)
food("pesto", "Pesto", ["pesto", "basil pesto"], "Sauce, pesto, ready-to-serve, refrigerated", 6.3, 1.5, 617, 6.0, 20, f"{A}: nut/oil sauce, low", 190, 250)
food("ranch", "Ranch dressing", ["ranch dressing", "ranch"], "Salad dressing, ranch dressing, regular", 5.9, 0.0, 900, 7.0, 40, f"{A}: creamy dressing", None, 232)
food("dressing", "Salad dressing / vinaigrette", ["salad dressing", "vinaigrette", "italian dressing", "caesar dressing", "dressing"], "Salad dressing, italian dressing, commercial, regular", 10.7, 0.0, 1050, 4.0, 40, f"{A}: dressing", None, 235)
food("wine", "Wine", ["wine", "red wine", "white wine", "dry white wine", "dry red wine", "cooking wine", "sherry", "marsala", "vermouth", "sake", "mirin", "shaoxing wine", "rice wine"], "Alcoholic beverage, wine, table, red", 2.6, 0.0, 4, 0.0, 15, f"{A}: wine, little carbohydrate", None, 236)
food("beer", "Beer", ["beer", "lager", "ale", "stout", "pale ale", "ipa"], "Alcoholic beverage, beer, regular, all", 3.6, 0.0, 4, 0.0, 66, f"{M}: beer 66", 355, 237)
food("spirits", "Spirits", ["vodka", "rum", "whiskey", "whisky", "bourbon", "brandy", "gin", "tequila", "cognac", "liqueur", "kahlua", "amaretto", "grand marnier", "triple sec"], "Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof", 0.0, 0.0, 1, 0.0, None, "no carbohydrate", None, 222)
food("water", "Water", ["water", "warm water", "cold water", "hot water", "boiling water", "ice water", "ice", "ice cubes", "sparkling water", "club soda"], "Water, tap", 0.0, 0.0, 4, 0.0, None, "no carbohydrate", None, 237)
food("coffee", "Coffee / tea", ["coffee", "brewed coffee", "espresso", "strong coffee", "tea", "green tea", "black tea"], "Beverages, coffee, brewed, prepared with tap water", 0.0, 0.0, 2, 0.0, None, "no carbohydrate", None, 237)
food("soda", "Soda", ["soda", "cola", "coke", "sprite", "ginger ale", "lemonade", "ginger beer", "tonic water"], "Beverages, carbonated, cola, regular", 10.6, 0.0, 4, 0.0, 63, f"{M}: cola 63", 355, 246)
food("salt", "Salt", ["salt", "table salt", "kosher salt", "sea salt", "flaky salt", "fine salt", "fine sea salt", "pickling salt", "salt to taste", "salt and pepper"], "Salt, table", 0.0, 0.0, 38758, 0.0, None, "no carbohydrate", None, 288)
food("salt-seasoned", "Seasoned salt", ["garlic salt", "celery salt", "seasoned salt", "seasoning salt", "lawry's", "onion salt", "old bay", "cajun seasoning", "creole seasoning", "everything bagel seasoning", "lemon pepper"], "Spices, garlic salt (branded average)", 15.0, 3.0, 27000, 0.2, 30, f"{A}: seasoning, small amounts", None, 250)
food("baking-powder", "Baking powder", ["baking powder"], "Leavening agents, baking powder, double-acting, sodium aluminum sulfate", 27.7, 0.2, 10600, 0.0, 65, f"{A}: starch filler, small amounts", None, 192)
food("baking-soda", "Baking soda", ["baking soda", "bicarbonate of soda", "bicarb", "bicarbonate"], "Leavening agents, baking soda", 0.0, 0.0, 27360, 0.0, None, "no carbohydrate", None, 220)
food("chili-powder", "Chili powder", ["chili powder", "chilli powder"], "Spices, chili powder", 49.7, 34.8, 1640, 2.5, 30, f"{A}: spice, small amounts", None, 128)
food("taco-seasoning", "Taco seasoning", ["taco seasoning", "fajita seasoning", "ranch seasoning", "onion soup mix", "dry onion soup mix"], "Taco seasoning mix, dry (branded average)", 55.0, 12.0, 5000, 0.5, 65, f"{A}: starch/sugar filler, small amounts", 28, 128)
food("curry-powder", "Curry powder", ["curry powder", "garam masala", "madras curry powder", "ras el hanout", "berbere", "five spice", "chinese five spice", "za'atar", "zaatar"], "Spices, curry powder", 55.8, 53.2, 52, 1.2, 30, f"{A}: spice, small amounts", None, 100)
food("spices", "Spice, dried", ["cumin", "ground cumin", "cumin seeds", "paprika", "smoked paprika", "sweet paprika", "cinnamon", "ground cinnamon", "cinnamon stick", "cinnamon sticks", "nutmeg", "ground nutmeg", "oregano", "dried oregano", "dried thyme", "dried basil", "dried rosemary", "dried parsley", "dried dill", "italian seasoning", "herbes de provence", "turmeric", "ground turmeric", "coriander", "ground coriander", "coriander seeds", "cayenne", "cayenne pepper", "black pepper", "ground black pepper", "pepper", "white pepper", "peppercorns", "black peppercorns", "red pepper flakes", "crushed red pepper", "chili flakes", "chilli flakes", "garlic powder", "onion powder", "ginger powder", "ground ginger", "cloves", "ground cloves", "whole cloves", "cardamom", "cardamom pods", "allspice", "bay leaves", "bay leaf", "mustard seeds", "mustard powder", "dry mustard", "fennel seeds", "caraway seeds", "star anise", "saffron", "sumac", "dried chili", "dried chilies", "dried chiles", "ancho chili powder", "chipotle powder", "poultry seasoning", "pumpkin pie spice", "apple pie spice", "dried mint", "marjoram", "celery seed", "anise", "juniper berries", "nutritional yeast", "msg", "cream of tartar", "food coloring", "spice", "seasoning", "dried herbs"], "Spices, cumin seed", 44.2, 10.5, 168, 1.5, 30, f"{A}: spice, small amounts", 0.5, 100)
food("gelatin", "Gelatin", ["gelatin", "gelatine", "unflavored gelatin", "agar agar", "agar", "pectin", "xanthan gum"], "Gelatins, dry powder, unsweetened", 0.0, 0.0, 196, 0.0, None, "no carbohydrate", 7, 150)
food("protein-powder", "Protein powder", ["protein powder", "whey protein", "collagen powder"], "Whey protein powder isolate (branded average)", 6.0, 1.0, 200, 0.5, 15, f"{A}: protein powder, low", 30, 120)

ids = [f["id"] for f in F]
assert len(ids) == len(set(ids)), "duplicate ids"
kws = {}
for f in F:
    for k in f["keywords"]:
        assert k == normalize(k) and k, f"keyword not normalized: {k!r}"
        assert k not in kws, f"keyword {k!r} in both {kws[k]} and {f['id']}"
        kws[k] = f["id"]
out = pathlib.Path(__file__).resolve().parent.parent / "KitchenBuddyKit/Sources/KitchenCore/Resources/foods.json"
doc = {
    "version": VERSION,
    "nutrientSource": "USDA FoodData Central (SR Legacy and Foundation Foods), per 100 g edible portion; a few branded averages where USDA has no generic entry",
    "glycemicIndexSource": "Atkinson FS, Foster-Powell K, Brand-Miller JC. International Tables of Glycemic Index and Glycemic Load Values: 2008. Diabetes Care 2008;31(12):2281–2283; and the 2021 update, Am J Clin Nutr 2021;114(5):1625–1632",
    "foods": F,
}
out.write_text(json.dumps(doc, ensure_ascii=False, indent=1, sort_keys=False) + "\n")
print(f"wrote {out} — {len(F)} foods, {len(kws)} keywords")
